=== yessinrekik/lsi3/web_service/tp1/bin/cinema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/cinema" xmlns:tns="http://www.example.org/cinema" elementFormDefault="qualified">

    <complexType name="Film">
    	<sequence>
    		<element name="titre" type="string"></element>
    		<element name="annee" type="string"></element>
    		<element name="realisateur" type="string"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="Cinema">
    	<sequence>
    		<element name="Film" type="tns:Film"></element>
    		<element name="Producteur" type="tns:Producteur"></element>
    	</sequence>
    </complexType>

    <complexType name="Producteur">
    	<sequence>
    		<element name="nom" type="string"></element>
    		<element name="Film" type="tns:Film"></element>
    	</sequence>
    </complexType>

    <element name="Cinema" type="tns:Cinema"></element>
</schema>

=== yessinrekik/lsi3/web_service/tp1/src/cinema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Cinema xmlns:tns="http://www.example.org/cinema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/cinema cinema.xsd ">
  <tns:Film id="lb78" type="comedie">
    <tns:titre>Les Bronzes</tns:titre>
    <tns:annee>1978</tns:annee>
    <tns:realisateur>Patrice Leconte</tns:realisateur>
  </tns:Film>
 
  
  
  <tns:Producteur>
    <tns:nom>Daniel Toscan du Plantier</tns:nom>
    <tns:Film>
      <tns:titre>Les Bronzes</tns:titre>
      <tns:annee>1978</tns:annee>
      <tns:realisateur>Patrice Leconte</tns:realisateur>
    </tns:Film>
  </tns:Producteur>
</tns:Cinema>
